# Generated by Django 4.1.1 on 2022-09-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_is_open_question_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='question',
        ),
    ]
