# Generated by Django 4.1.1 on 2022-10-17 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_answer_number_of_appearances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='number_of_appearances',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.question'),
        ),
    ]
